/**
 * Oracle Autonomous Database Initialization Script
 * Creates all required tables for Agent Platform
 */
const oracledb = require("oracledb");
const fs = require("fs");
const path = require("path");

const walletDir = path.join(__dirname, "wallet");

const config = {
  user: process.env.ORACLE_USER || "ADMIN",
  password: process.env.ORACLE_PASSWORD || "AgentPlat2026#Secure",
  connectString: process.env.ORACLE_CONNECTION_STRING || "agentplatdb_tp",
  configDir: walletDir,
  walletLocation: walletDir,
  walletPassword: process.env.ORACLE_WALLET_PASSWORD || "WalletPass2026#",
};

// DDL statements (split from schema.sql)
const ddlStatements = [
  // Users
  `CREATE TABLE USERS (
    ID VARCHAR2(30) PRIMARY KEY,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255),
    NAME VARCHAR2(255),
    IMAGE VARCHAR2(500),
    EMAIL_VERIFIED TIMESTAMP WITH TIME ZONE,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    TEAM_ID VARCHAR2(30),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
  )`,

  // Accounts
  `CREATE TABLE ACCOUNTS (
    ID VARCHAR2(30) PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    PROVIDER VARCHAR2(50) NOT NULL,
    PROVIDER_ACCOUNT_ID VARCHAR2(255) NOT NULL,
    REFRESH_TOKEN CLOB,
    ACCESS_TOKEN CLOB,
    EXPIRES_AT NUMBER(10),
    TOKEN_TYPE VARCHAR2(50),
    SCOPE VARCHAR2(500),
    ID_TOKEN CLOB,
    SESSION_STATE VARCHAR2(255),
    CONSTRAINT FK_ACCOUNTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_ACCOUNTS_PROVIDER UNIQUE (PROVIDER, PROVIDER_ACCOUNT_ID)
  )`,

  // Sessions
  `CREATE TABLE SESSIONS (
    ID VARCHAR2(30) PRIMARY KEY,
    SESSION_TOKEN VARCHAR2(255) UNIQUE NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    EXPIRES TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
  )`,

  // Verification Tokens
  `CREATE TABLE VERIFICATION_TOKENS (
    IDENTIFIER VARCHAR2(255) NOT NULL,
    TOKEN VARCHAR2(255) UNIQUE NOT NULL,
    EXPIRES TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT UQ_VERIFICATION UNIQUE (IDENTIFIER, TOKEN)
  )`,

  // Teams
  `CREATE TABLE TEAMS (
    ID VARCHAR2(30) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    SLUG VARCHAR2(255) UNIQUE NOT NULL,
    DESCRIPTION CLOB,
    IMAGE VARCHAR2(500),
    PLAN VARCHAR2(20) DEFAULT 'FREE' NOT NULL,
    STRIPE_CUSTOMER_ID VARCHAR2(255),
    STRIPE_SUBSCRIPTION_ID VARCHAR2(255),
    OWNER_ID VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_TEAMS_OWNER FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
  )`,

  // Team Invitations
  `CREATE TABLE TEAM_INVITATIONS (
    ID VARCHAR2(30) PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    TEAM_ID VARCHAR2(30) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_INVITATIONS_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_INVITATION UNIQUE (EMAIL, TEAM_ID)
  )`,

  // Agents
  `CREATE TABLE AGENTS (
    ID VARCHAR2(30) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION CLOB,
    ICON VARCHAR2(50),
    SYSTEM_PROMPT CLOB NOT NULL,
    MODEL VARCHAR2(100) DEFAULT 'gpt-4o' NOT NULL,
    PROVIDER VARCHAR2(50) DEFAULT 'OPENAI' NOT NULL,
    TEMPERATURE NUMBER(5,2) DEFAULT 0.7 NOT NULL,
    MAX_TOKENS NUMBER(10),
    TOOLS CLOB DEFAULT '[]' NOT NULL,
    WORKFLOW CLOB,
    IS_PUBLIC NUMBER(1) DEFAULT 0 NOT NULL,
    IS_TEMPLATE NUMBER(1) DEFAULT 0 NOT NULL,
    USAGE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    RATING NUMBER(5,2),
    USER_ID VARCHAR2(30) NOT NULL,
    TEAM_ID VARCHAR2(30),
    CATEGORY VARCHAR2(100),
    TAGS VARCHAR2(500),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_AGENTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_AGENTS_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)
  )`,

  // Conversations
  `CREATE TABLE CONVERSATIONS (
    ID VARCHAR2(30) PRIMARY KEY,
    TITLE VARCHAR2(500),
    MODEL VARCHAR2(100) DEFAULT 'gpt-4o' NOT NULL,
    PROVIDER VARCHAR2(50) DEFAULT 'OPENAI' NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    AGENT_ID VARCHAR2(30),
    IS_ARCHIVED NUMBER(1) DEFAULT 0 NOT NULL,
    IS_PINNED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_CONV_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CONV_AGENT FOREIGN KEY (AGENT_ID) REFERENCES AGENTS(ID)
  )`,

  // Messages
  `CREATE TABLE MESSAGES (
    ID VARCHAR2(30) PRIMARY KEY,
    ROLE VARCHAR2(20) NOT NULL,
    CONTENT CLOB NOT NULL,
    TOOL_CALLS CLOB,
    TOOL_RESULTS CLOB,
    MODEL VARCHAR2(100),
    TOKENS NUMBER(10),
    CONVERSATION_ID VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONS(ID) ON DELETE CASCADE
  )`,

  // API Keys
  `CREATE TABLE API_KEYS (
    ID VARCHAR2(30) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    KEY_VALUE VARCHAR2(255) UNIQUE NOT NULL,
    HASHED_KEY VARCHAR2(255) NOT NULL,
    PERMISSIONS VARCHAR2(100) DEFAULT 'read,write' NOT NULL,
    RATE_LIMIT NUMBER(10) DEFAULT 100 NOT NULL,
    LAST_USED_AT TIMESTAMP WITH TIME ZONE,
    USAGE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    IS_REVOKED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_APIKEYS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
  )`,

  // Usage Records
  `CREATE TABLE USAGE_RECORDS (
    ID VARCHAR2(30) PRIMARY KEY,
    PROVIDER VARCHAR2(50) NOT NULL,
    MODEL VARCHAR2(100) NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    INPUT_TOKENS NUMBER(10) DEFAULT 0 NOT NULL,
    OUTPUT_TOKENS NUMBER(10) DEFAULT 0 NOT NULL,
    TOTAL_TOKENS NUMBER(10) DEFAULT 0 NOT NULL,
    COST NUMBER(10,4) DEFAULT 0 NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_USAGE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
  )`,

  // User Provider Keys
  `CREATE TABLE USER_PROVIDER_KEYS (
    ID VARCHAR2(30) PRIMARY KEY,
    PROVIDER VARCHAR2(50) NOT NULL,
    ENCRYPTED_KEY VARCHAR2(500) NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_PROVKEYS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_USER_PROVIDER UNIQUE (USER_ID, PROVIDER)
  )`,

  // Indexes
  `CREATE INDEX IDX_MSG_CONV_ID ON MESSAGES(CONVERSATION_ID, CREATED_AT)`,
  `CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL)`,
  `CREATE INDEX IDX_CONV_USER_ID ON CONVERSATIONS(USER_ID, UPDATED_AT)`,
  `CREATE INDEX IDX_AGENTS_USER_ID ON AGENTS(USER_ID)`,
  `CREATE INDEX IDX_USAGE_USER_ID ON USAGE_RECORDS(USER_ID, CREATED_AT)`,
  `CREATE INDEX IDX_PROVKEYS_USER ON USER_PROVIDER_KEYS(USER_ID)`,
];

async function initDatabase() {
  let connection;

  try {
    console.log("Connecting to Oracle Autonomous Database...");
    console.log(`  User: ${config.user}`);
    console.log(`  Connect String: ${config.connectString}`);
    console.log(`  Wallet Dir: ${config.configDir}`);

    connection = await oracledb.getConnection(config);
    console.log("Connected successfully!\n");

    let created = 0;
    let skipped = 0;
    let errors = 0;

    for (const ddl of ddlStatements) {
      const match = ddl.match(
        /CREATE\s+(TABLE|INDEX)\s+(\w+)/i
      );
      const objType = match ? match[1].toUpperCase() : "OBJECT";
      const objName = match ? match[2] : "UNKNOWN";

      try {
        await connection.execute(ddl);
        console.log(`  [OK] Created ${objType}: ${objName}`);
        created++;
      } catch (err) {
        if (err.errorNum === 955) {
          // ORA-00955: name is already used
          console.log(`  [SKIP] ${objType} ${objName} already exists`);
          skipped++;
        } else if (err.errorNum === 1408) {
          // ORA-01408: index already exists
          console.log(`  [SKIP] INDEX ${objName} already exists`);
          skipped++;
        } else {
          console.error(`  [ERROR] ${objType} ${objName}: ${err.message}`);
          errors++;
        }
      }
    }

    // Add FK for USERS.TEAM_ID -> TEAMS
    try {
      await connection.execute(
        "ALTER TABLE USERS ADD CONSTRAINT FK_USERS_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)"
      );
      console.log("  [OK] Added FK: USERS.TEAM_ID -> TEAMS");
    } catch (err) {
      if (err.errorNum === 2275 || err.errorNum === 2264) {
        console.log("  [SKIP] FK USERS.TEAM_ID already exists");
      }
    }

    console.log(`\nDone! Created: ${created}, Skipped: ${skipped}, Errors: ${errors}`);

    // Test connection by inserting a test user
    console.log("\nVerifying with test query...");
    const result = await connection.execute("SELECT 1 AS TEST_VALUE FROM DUAL");
    console.log("  Test query result:", result.rows);
    console.log("\nDatabase initialization complete!");
  } catch (err) {
    console.error("Database initialization failed:", err);
    process.exit(1);
  } finally {
    if (connection) {
      await connection.close();
    }
  }
}

initDatabase();
